version: '2'
services:
  zookeeper:
    image: swr.cn-east-3.myhuaweicloud.com/enmotech/debezium/enmo_zookeeper:1.3
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: swr.cn-east-3.myhuaweicloud.com/enmotech/debezium/enmo_kafka:1.3
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  opengauss:
    image: swr.cn-east-3.myhuaweicloud.com/enmotech/debezium/enmo_opengauss:1.3
    privileged : true
    ports:
     - 5432:5432
    environment:
     - GS_PASSWORD=Enmo@123
  connect:
    image: swr.cn-east-3.myhuaweicloud.com/enmotech/debezium/enmo_connect:1.3
    ports:
     - 8083:8083
    links:
     - kafka
     - opengauss
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
